POST http://localhost:5555/API/Author/resources/author
Content-Type: application/json

{
  "name": "nr_0",
  "reward": 0
}

###
GET http://localhost:5555/API/Author/resources/author


###
GET http://localhost:5555/API/Author/resources/author/1

###
PUT http://localhost:5555/API/Author/resources/author/1/9/1
Content-Type: application/json

{
  "name": "hmmm",
  "reward": 9
}