server:
  port: 5555

spring:
  application:
    name: BlogGateway

  cloud:
    gateway:
      routes:
        - id: Blogroute
          uri: lb://BlogSERVICE
          predicates:
            - Path=/API/blog/**
          filters:
            - RewritePath=/API/blog(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
        - id: Commentroute
          uri: lb://CommentSERVICE
          predicates:
            - Path=/API/Comment/**
          filters:
            - RewritePath=/API/Comment(?<segment>.*), $\{segment}
            - name: Retry
              args:
                retries: 3
                statutes: NOT_FOUND, INTERNAL_SERVER_ERROR
                methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    # fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway

