server:
  port: 8761

spring:
  application:
    name: BlogRegistry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka   # disables peer replication
  server:
    use-read-only-response-cache: false
