POST http://localhost:5555/API/blog/resources/blogs
Content-Type: application/json

{
  "attractions": "test ADD_2",
  "description": "this is a test",
  "author": {
    "id": 1
  },
  "popular": 10
}
###
PUT http://localhost:5555/API/blog/resources/blogs/1
Content-Type: application/json

{
  "attractions": "update test ADD",
  "description": "this is a update",
  "author": {
    "id": 1,
    "name": "nr_1_b_Update",
    "reward": 0
  },
  "popular": 19
}

###
GET http://localhost:5555/API/blog/resources/blogs/1


###
GET http://localhost:5555/API/blog/resources/blogs


###
DELETE http://localhost:5555/API/blog/resources/blogs/2
